Repository inclusive-design/wecount.inclusivedesign.ca, pull requests merged in 2020-04, with the labels that each got.

#135 Layout single views
  assets/css/abstracts/_variables.scss
  assets/css/components/_components.scss
  assets/css/components/_news-and-views.scss
  assets/css/components/_post-article.scss
  components/PostArticle.vue
  pages/tag/_query/index.vue
  pages/views/_slug/index.vue
Labels: enhancement

#134 Style page content
  assets/css/abstracts/_variables.scss
  assets/css/components/_aside.scss
  assets/css/components/_components.scss
  assets/css/layout/_layout.scss
  components/Aside.vue
  layouts/default.vue
Labels: enhancement

#148 fix: improve styling for image captions (fix #147)
  assets/css/layout/_layout.scss
Labels: bug

#149 feat: use Avenir for logotype (fixes #145)
  assets/css/components/_brand.scss
  assets/css/layout/_header.scss
  assets/images/logotype.svg
  components/Brand.vue
Labels: enhancement

#150 Issue-144: Add unique page titles.
  pages/_slug/index.vue
  pages/index.vue
  pages/news/index.vue
  pages/news/page/_num/index.vue
  pages/search/_query/index.vue
  pages/tag/_query/index.vue
  pages/views/_slug/index.vue
  pages/views/index.vue
  pages/views/page/_num/index.vue
Labels: enhancement

#151 Padding at main bottom
  assets/css/components/_cards.scss
  assets/css/components/_pagination.scss
  assets/css/layout/_layout.scss
Labels: enhancement

#152 Remove tools ourdata from nav
  components/NavBar.vue
Labels: enhancement

#153 Hide tools card
  assets/css/components/_cards.scss
  pages/index.vue
Labels: enhancement

#154 Hide nav social at footer
  components/Footer.vue
Labels: enhancement

#157 Issue-156: Fix the focus/hover styling with footer SVGs on mobile devices
  assets/css/layout/_footer.scss
Labels: bug

#161 fix: swap categories for News and Views
  nuxt.config.js
  store/actions.js
Labels: enhancement

#160 fix: background position (resolves #142)
  assets/css/layout/_header.scss
  assets/css/layout/_layout.scss
  assets/images/background.svg
Labels: enhancement

#155 feat: add meta description and Open Graph image (fix #146)
  assets/config.js
  assets/css/layout/_footer.scss
  nuxt.config.js
  pages/_slug/index.vue
  pages/index.vue
  pages/news/index.vue
  pages/news/page/_num/index.vue
  pages/search/_query/index.vue
  pages/tag/_query/index.vue
  pages/views/_slug/index.vue
  pages/views/index.vue
  pages/views/page/_num/index.vue
  static/favicon.png
  static/icon.png
  static/img/We Count logos_colour and bw-01.png
  static/img/canada_logo.png
  static/img/cancel.png
  static/img/list-menu.png
  static/og-image.png
Labels: enhancement

#164 chore(deps): run npm update
  package-lock.json
  package.json
Labels: enhancement

#165 fix: resolve validation errors (fixes #163)
  assets/css/components/_cards.scss
  components/Header.vue
  components/Pagination.vue
  pages/index.vue
Labels: bug

#168 added to between "need" and "install".
  README.md
Labels: documentation

#175 fix: add ARIA role to search results message (fixes #173)
  pages/search/_query/index.vue
Labels: bug

#176 feat: use excerpts from WordPress API (resolves #172)
  components/NewsGrid.vue
  components/NewsItem.vue
  shared/DataFetcher.js
Labels: enhancement

#183 fix: adjust styles, replace background image
  assets/css/components/_news-and-views.scss
  assets/css/layout/_header.scss
  assets/css/layout/_layout.scss
  assets/images/background-distribution.svg
  assets/images/background.svg
Labels: enhancement

#190 Issue-177: Not to show the tag area when there's no tags.
  components/PostArticle.vue
Labels: bug

#192 fix: resolve broken Netlify link
  components/Footer.vue
Labels: bug

#185 docs: add contributing guide (resolves #182)
  .github/CONTRIBUTING.md
  README.md
  package-lock.json
  package.json
Labels: documentation

#194 fix: update linter configurations (resolves #186, resolves #187)
  .eslintrc.js
  assets/config.js
  assets/css/abstracts/_functions.scss
  assets/css/base/_base.scss
  assets/css/components/_aside.scss
  assets/css/components/_brand.scss
  assets/css/components/_cards.scss
  assets/css/components/_news-and-views.scss
  assets/css/components/_pagination.scss
  assets/css/components/_post-article.scss
  assets/css/layout/_footer.scss
  assets/css/layout/_header.scss
  assets/css/layout/_layout.scss
  commitlint.config.js
  components/Aside.vue
  components/Brand.vue
  components/ContactInfo.vue
  components/Footer.vue
  components/Funders.vue
  components/Header.vue
  components/NewsGrid.vue
  components/NewsItem.vue
  components/PageArticle.vue
  components/Pagination.vue
  components/PostArticle.vue
  components/Posts.vue
  components/SocialMedia.vue
  layouts/default.vue
  layouts/error.vue
  nuxt.config.js
  pages/_slug/index.vue
  pages/index.vue
  pages/news/index.vue
  pages/news/page/_num/index.vue
  pages/search/_query/index.vue
  pages/tag/_query/index.vue
  pages/views/_slug/index.vue
  pages/views/index.vue
  pages/views/page/_num/index.vue
  shared/DataFetcher.js
  shared/Utils.js
  store/actions.js
  store/getters.js
  store/index.js
  store/mutations.js
  store/state.js
  stylelint.config.js
Labels: enhancement

#195 feat: configure PostCSS/Autoprefixer (resolves #188)
  .browserslistrc
Labels: enhancement

#196 Issue-170: Auto generate navigation menus based on the API response.
  assets/css/layout/_footer.scss
  components/Footer.vue
  components/Header.vue
  components/NavBar.vue
  shared/DataFetcher.js
  shared/Utils.js
  store/actions.js
Labels: enhancement

#199 chore(docs): update license
  LICENSE
  package.json
Labels: documentation

#200 chore: add dedicated development endpoint for API (fix #166)
  README.md
  assets/config.js
Labels: enhancement

#201 Create static routes
  components/NewsItem.vue
  nuxt.config.js
  pages/_slug/index.vue
  pages/index.vue
  shared/DataFetcher.js
  shared/Utils.js
Labels: enhancement

#209 fix: revert the auto generation of the navigation menu
  assets/css/layout/_footer.scss
  components/Footer.vue
  components/Header.vue
  components/NavBar.vue
  shared/DataFetcher.js
  shared/Utils.js
  store/actions.js
Labels: bug

#218 Style nav item
  src/scss/layout/_header.scss
Labels: enhancement
