Repository inclusive-design/wecount.inclusivedesign.ca, pull requests merged in 2020-02, with the labels that each got.

#32 Add information for running/building the site (fix #29)
  README.md
Labels: documentation

#25 Missing prop type (resolve #10)
  components/Post.vue
  store/actions.js
Labels: bug

#31 Spaces to tabs (resolve #26)
  .eslintrc.js
  components/Aside.vue
  components/Footer.vue
  components/Header.vue
  components/Post.vue
  components/Search.vue
  jsconfig.json
  layouts/default.vue
  layouts/error.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/About.vue
  pages/index.vue
  pages/news/_slug/index.vue
  pages/news/about.vue
  pages/news/index.vue
  pages/news/news.vue
  pages/news/we-count.vue
  pages/search/_query/index.vue
  pages/tag/_query/index.vue
Labels: bug

#30 Next not defined (fix #27)
  nuxt.config.js
Labels: bug

#35 Query images
  components/Post.vue
Labels: enhancement

#36 Tooling: add ESLint to CI (resolve #28)
  package.json
Labels: enhancement

#38 fix: generate error should fail CI (resolves #37)
  package.json
Labels: bug

#50 Set up base components
  components/Brand.vue
  components/ContactInfo.vue
  components/Footer.vue
  components/Funders.vue
  components/Header.vue
  components/NavBar.vue
  components/SearchForm.vue
  components/SocialMedia.vue
  layouts/default.vue
Labels: enhancement

#52 Component header brand
  components/Brand.vue
  components/Footer.vue
  components/Header.vue
  layouts/default.vue
Labels: enhancement

#54 Component header search
  components/ContactInfo.vue
  components/Funders.vue
  components/SearchForm.vue
  components/SocialMedia.vue
Labels: enhancement

#55 Main article
  components/Article.vue
Labels: enhancement

#56 fix: moved main css to assets directory
  assets/css/main.css
  nuxt.config.js
Labels: enhancement

#57 Main aside
  components/Article.vue
  components/Aside.vue
Labels: enhancement

#59 Footer contact info
  assets/config.js
  components/ContactInfo.vue
  static/img/idrc.png
Labels: enhancement

#61 feat: added social media component
  assets/config.js
  components/SocialMedia.vue
Labels: enhancement

#60 feat: added funders component
  assets/config.js
  components/ContactInfo.vue
  components/Funders.vue
  components/SocialMedia.vue
Labels: enhancement

#58 tooling: add stylelint
  assets/css/main.css
  components/Footer.vue
  components/Header.vue
  components/Post.vue
  layouts/default.vue
  package-lock.json
  package.json
  pages/index.vue
  pages/news/_slug/index.vue
  pages/news/we-count.vue
  stylelint.config.js
Labels: enhancement

#66 tooling: add markdownlint (resolves #33)
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .markdownlint.json
  README.md
  package-lock.json
  package.json
Labels: enhancement

#72 feat: simplified error-page
  layouts/error.vue
Labels: enhancement

#68 feat: added NewsItem component
  components/NewsGrid.vue
  components/NewsItem.vue
  components/Post.vue
  pages/news-and-views/index.vue
  pages/search/_query/index.vue
  pages/tag/_query/index.vue
  store/actions.js
Labels: enhancement

#75 fix: mixed content errors (resolves #74)
  store/actions.js
Labels: bug

#51 fix: remove bootstrap vue
  components/PostArticle.vue
  components/Search.vue
  nuxt.config.js
  package-lock.json
  package.json
  pages/news-and-views/_slug/index.vue
  pages/search/_query/index.vue
  pages/tag/_query/index.vue
  plugins/bootstrap-vue.js
Labels: enhancement

#82 feat: add proper action route to search form
  components/SearchForm.vue
Labels: enhancement

#83 feat: rename Article component to PageArticle
  components/PageArticle.vue
  layouts/error.vue
  pages/about.vue
  pages/inclusion-challenges.vue
  pages/index.vue
  pages/our-data.vue
  pages/tools.vue
Labels: enhancement

#85 feat: run actions on pull requests (resolves #84)
  .github/workflows/main.yml
Labels: enhancement

#86 feat: add precommit hooks to lint on commit
  assets/css/main.css
  commitlint.config.js
  package-lock.json
  package.json
Labels: enhancement
