Repository inclusive-design/wecount.inclusivedesign.ca, pull requests merged in 2024-03, with the labels that each got.

#1730 feat: apply proper themes to the cards used in homepage (resolves #1700)
  src/_includes/components/card.macro.njk
  src/_includes/layouts/page.njk
  src/_includes/svg/azure.svg
  src/_includes/svg/blue.svg
  src/_includes/svg/green.svg
  src/_includes/svg/yellow.svg
  src/assets/images/azure.svg
  src/assets/images/blue.svg
  src/assets/images/green.svg
  src/assets/images/yellow.svg
  src/assets/styles/abstracts/_variables.scss
  src/assets/styles/components/_cards.scss
Labels: enhancement

#1737 fix: remove border in default theme
  src/assets/styles/components/_cards.scss
Labels: enhancement

#1738 fix: issue with side navbar items' wordwrap
  src/assets/styles/components/_aside.scss
Labels: bug

#1742 ci: add Release Please action
  .github/workflows/release-please.yml
  .release-please-manifest.json
  release-please-config.json
Labels: dependencies, github_actions

#1752 chore(dep-devs): upgrade @commitlint/config-conventional
  .eslintrc.js
  .github/workflows/lint.yml
  commitlint.config.mjs
  package-lock.json
  package.json
Labels: dependencies
