Repository inclusive-design/wecount.inclusivedesign.ca, pull requests merged in 2024-02, with the labels that each got.

#1663 fix: vertical alignment issues for Image and Text widget
  src/scss/layout/_layout.scss
Labels: bug

#1682 feat: remove role-based authentication check (resolves #906)
  netlify.toml
  src/_includes/components/footer.njk
  src/_includes/layouts/base.njk
  src/assets/styles/components/_components.scss
  src/assets/styles/components/_identity.scss
Labels: bug, enhancement

#1683 feat: add support for image captions (resolves #1670)
  src/admin/cms.js
  src/assets/styles/layout/_layout.scss
  src/collections/initiatives/environmental-scan-canadian-postsecondary-education-and-ai-ethics.md
  src/collections/initiatives/the-accessibility-ecosystem-proposal.md
  src/collections/initiatives/the-future-of-work-and-disability.md
  src/collections/pages/badges.md
  src/shortcodes/image-and-text.js
Labels: enhancement

#1684 feat: use lite-youtube-embed for YouTube videos
  eleventy.config.js
  package-lock.json
  package.json
  src/_includes/layouts/base.njk
  src/assets/styles/base/_base.scss
  src/assets/styles/layout/_layout.scss
  src/shortcodes/youtube.js
Labels: enhancement

#1685 fix: expander style issue
  src/assets/styles/base/_base.scss
  src/shortcodes/expander.js
Labels: bug

#1688 chore: sync changes from dev
  eleventy.config.js
  package-lock.json
  package.json
  src/_includes/layouts/base.njk
  src/admin/cms.js
  src/admin/config.yml
  src/assets/styles/base/_base.scss
  src/assets/styles/layout/_layout.scss
  src/collections/initiatives/environmental-scan-canadian-postsecondary-education-and-ai-ethics.md
  src/collections/initiatives/the-accessibility-ecosystem-proposal.md
  src/collections/initiatives/the-future-of-work-and-disability.md
  src/collections/pages/badges.md
  src/shortcodes/expander.js
  src/shortcodes/image-and-text.js
  src/shortcodes/youtube.js
Labels: enhancement
